version: "3.9"

services:
  php-api:
    image: php:8.3-apache
    volumes:
      - ./lab02prep/app:/var/www/html
    env_file:
      - ./.env
    restart: unless-stopped

  cron-runner:
    build:
      context: .
    depends_on:
      - php-api
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      - ./error.log:/app/error.log
    restart: unless-stopped
